export * from './Home';
export * from './Products';
export * from './About';
export * from './Privacy';
export * from './Catalogo';
export * from './ContactUs';
export * from './Login';
export * from './ChangePass';
export * from './TheProfile';